### PR TITLE
Fixes TAR 09 Fixed Contribution update Button

### PR DESCRIPTION
**Pull request by acdczlc**

### CODE REVIEW

**Comment by LegendaryZReborn** [comment]
Hey, it seems as though the update for the contribution is not working. It might have been overwritten by someone else's commit. Sorry about that. Can you redo it and check all of your other fixes as well?

**Comment by acdczlc** [comment]
I just checked it and nothing was overwritten, it is the same code that was working yesterday. In class you said you might have done something that broke it, do you know what that was?

**Comment by LegendaryZReborn** [comment]
It wasnt pertaining to the update. What happened was I was trying to add an
event so I could do the live updates but when i did, areas of the code that
mentio ed IDTextField said it didnt exist.

I fixed it by readding another invisible IDTextField to the frame

**Comment by acdczlc** [comment]
Ok I will try to fix it but I have no idea what it could be

**Comment by acdczlc** [comment]
I have no idea what is happening but i didn't change anything and ran it a few times with debug on and it appeared to be doing everything it is supposed to, but wasn't updating. I then tried to run it again and it works every time now. The box in the current version is small but not invisible I can fix it, but I have no idea what could be wrong that causes it to only work sometimes.

**Comment by LegendaryZReborn** [comment]
The box is changed to invisible only when it runs, checm the constructor
for the contribution frame. Helps to keep track of it.

**Comment by acdczlc** [comment]
I just made it invisible and did a pull request it seemed to fix it. I tried it 3 times and it worked every time.

**Comment by LegendaryZReborn** [comment]
Ok

**Comment by LegendaryZReborn** [comment]
Ill test it again later

**Pull request merged**
